# Generated by Django 2.2.12 on 2020-06-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200630_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
